elasticsearch {
  index_settings {
    number_of_shards: 3
    number_of_replicas: 1
    index_mapper_dynamic: false
    index_retries: 10  # Number of times to retry indexing a document
    index_retry_timeout: 10  # Seconds to wait between each index retry
  }
}

connections {
  elasticsearch {
    db: ""
    host: "localhost"
    port: 9200
    user: "elastic"
    password: "changeme"
  }
}

logging {
  level: "DEBUG"
  handlers: "console"
}
