crypto: [ETH]  # , USDT]

# For standalone preprocessing runs
preprocessing {
  "normalize": true,
  "window_size": 60,
  "predictor_params": {
    "lookahead_days": 1,
    "prob_sell": 1,
    "starting_investment": 100,
    "prob_buy": 1,
    "daily_allowance": 5
  },
  "end_date": "today",
  "price_column": "Close",
  "normalize_by_row": false,
  "save_data": false,
  "predictor_cls": "BiffPredictor",
  "save_roi": true,
  "start_date": "2018-01-01"
}

logging {
    level: "INFO"
    handlers: "console"
}
