crypto: [ETH, BTC, XRP, LTC]
save_preprocessing_data: false
save_preprocessing_roi: true

preprocessing {
    start_date: "2018-06-01"  # YYYY-MM-DD
    end_date: "today"  # YYYY-MM-DD, today, yesterday
    window_size: 10
    normalize: false
    normalize_by_row: false
    standardize: false
    price_column: "Close"
    predictor_cls: ["BiffPredictor", "BiffPredictorSmart"]
    predictor_params {
        prob_buy: 1,
        prob_sell: 1,
        starting_investment: 100,
        daily_allowance: 5,
        lookahead_days: [1, 2, 3, 4, 5]
    }
}

logging {
    level: "INFO"
    handlers: "console"
}
