crypto: "ETH"  # BTC, XRP, LTC, USDT

# For standalone preprocessing runs
preprocessing {
    start_date: "2018-01-01"  # YYYY-MM-DD
    end_date: "today"  # YYYY-MM-DD, today, yesterday
    window_size: 30
    normalize: true
    normalize_by_row: false
    price_column: "Close"
    save_roi: true
    save_data: false
    predictor_cls: "BiffPredictorSmart"
    predictor_params {
        prob_buy: 0.8,
        prob_sell: 0.8,
        starting_investment: 100,
        daily_allowance: 5,
        lookahead_days: 1
    }
}

logging {
    level: "INFO"
    handlers: "console"
}
