crypto: "LTC"  # BTC, XRP, LTC, USDT
save_preprocessing_data: true
save_preprocessing_roi: false
save_training_results: false
save_training_model: true

preprocessing {
  "normalize": true,
  "window_size": 60,
  "predictor_params": {
    "lookahead_days": 4,
    "prob_sell": 1,
    "starting_investment": 100,
    "prob_buy": 1,
    "daily_allowance": 5
  },
  "end_date": "2019-05-04",
  "price_column": "Close",
  "normalize_by_row": true,
  "predictor_cls": "BiffPredictorSmart",
  "start_date": "2017-01-01"
}

training {
  "dev_size": 0.5,
  "shuffle_data": true,
  "training_size": 0.7,
  "cv_folds": 4
}

logging {
    level: "DEBUG"
    handlers: "console"
}
