crypto: ETH
save_preprocessing_data: true
save_preprocessing_roi: false
save_training_results: false
save_training_model: true

preprocessing {
    start_date: "2018-01-01"  # YYYY-MM-DD
    end_date: "2019-09-30"  # YYYY-MM-DD, today, yesterday
    window_size: 60
    normalize: true
    normalize_by_row: true
    standardize: false
    price_column: "Close"
    predictor_cls: BiffPredictor
    predictor_params {
        prob_buy: 1,
        prob_sell: 1,
        starting_investment: 100,
        daily_allowance: 5,
        lookahead_days: 4
    }
}

training {
    shuffle_data: true
}

deep_learning {
    neurons: 60,
    activation_function: "sigmoid"
}

logging {
    level: "INFO"
    handlers: "console"
}
