crypto: "ETH"  # BTC, XRP, LTC, USDT

preprocessing {
  "normalize": true,
  "window_size": 30,
  "predictor_params": {
    "lookahead_days": 4,
    "prob_sell": 1,
    "starting_investment": 100,
    "prob_buy": 1,
    "daily_allowance": 5
  },
  "end_date": "today",
  "price_column": "Close",
  "normalize_by_row": true,
  "save_data": true,
  "predictor_cls": "BiffPredictorSmart",
  "save_roi": false,
  "start_date": "2018-01-01"
}

training {
    shuffle_data: false
}

logging {
    level: "INFO"
    handlers: "console"
}