crypto: "BTC"
save_preprocessing_data: true
save_preprocessing_roi: false
save_training_results: false
save_training_model: true

preprocessing {
  "normalize": true,
  "window_size": 40,
  "predictor_params": {
    "lookahead_days": 2,
    "prob_sell": 1,
    "starting_investment": 100,
    "prob_buy": 1,
    "daily_allowance": 5
  },
  "end_date": "2019-09-30",
  "price_column": "Close",
  "normalize_by_row": true,
  "standardize": false,
  "predictor_cls": "BiffPredictor",
  "start_date": "2018-01-01"
}

training {
  "dev_size": 0.5,
  "shuffle_data": true,
  "training_size": 0.7,
  "cv_folds": 4
}

logging {
    level: "DEBUG"
    handlers: "console"
}
